### ISSUE TITLE
RichText block

### ISSUE THREAD

**Issue by Venutius** [CODESIGN2/gutenberg-shortcode-preview-block#6]
Thanks for this, it's really timely, I've done some limited testing and it seems to work well. One suggestion though is that you might like to create it using a RichText block. I've two reasons for this:

1. Some plugins (mine - BP Profile Shortcodes Extra, for example) add a tinyMCE menu item to insert their shortcode, so having richtext would allow users to select those shortcodes from the richtext menu.
2. Some shortcodes are designed to be inserted in the middle of sentences, to display (in my own case) for example the username of the person viewing the post.

**Comment by Lewiscowles1986** [comment]
Interesting use-case. I wonder if I could add a button to enable such a use-case, or if it's better to document another of my plugins, which would allow them to include a shortcode within their shortcode so that the content can be managed in another post (Custom post type for shared relocatable content).

I had also thought about a dropdown menu of all shortcodes (as it's trivial to enumerate), but the problem then is that the syntax isn't AFAIK easy to get to for all shortcodes.

**Comment by Venutius** [comment]
Yes I was thinking the same, a version of the classic block that included shortcode rendering on preview is probably exactly what is needed.

**Comment by Lewiscowles1986** [comment]
I was not proposing that. I was saying in the case such an experience was needed a workaround would be to use the classic editor experience.

Making classic editor rich-render, although interesting (it's the same as this, block focus shows editor outside of placeholder state, sends to REST-API, which runs through `the_content`); there is a lot more to consider. 

For example oEmbed, the fact the classic-editor was supposed to be an interactive preview by design (so you' be breaking that). 

Due to technologies available at the time it was written it was problematic because of the unlimited editing control. IMO Gutenberg is very much an admittance that such control is too difficult, it aims to be simpler, but more predictable and reliable (from what I've seen), offering atoms you can composite rather than trying AIO solutions.

further to this, you can copy and paste html from a classic block into this. It's not the best editing experience, but I feel like nothing will be once you get down to that complicated use-case. Shortcodes are too open a spec and implementation.

Consider the three workarounds

* Implement `wp.mce.view` for shortcodes & use classic editor
* Contribute to this with design, code, etc
* Use another plugin which allows you to yo-dawg shortcode in a shortcode using another post to handle the rich-content https://github.com/CODESIGN2/WordPress-Content-Sections `[content_section name="some-slug-of-a-content-section"]`

**Comment by Lewiscowles1986** [comment]
Apparently Gutenberg is launching without classic editor, so this might be problematic or impossible to implement. It's certainly not something I'm being asked by clients
